<a href="https://colab.research.google.com/github/YasminGarcia1210/MAT_APLICADAS03/blob/main/CUADERNO_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src=http://www.acofi.edu.co/eiei2016/wp-content/uploads/2016/09/Logo-Universidad-ICESI.jpg width="200" height="200" align="center">

#**<big><big>Matemáticas Aplicadas I</big></big><br><small>Depto. Matemáticas & Estadística / Facultad de Ingeniería</small><br><small>_*CUADERNO 2*_ ARREGLOS. </small>**

##Arreglos #

Un **array** en Python es un tipo de variable especial que puede alojar dentro de sí varios valores al mismo tiempo.

Es decir, no es que se alojen los datos en un mismo lugar al mismo tiempo, sino que se tienen una serie de contenedores que conforman el array y en cada uno de esos contenedores se guardan datos distintos

##Diferencias entre listas y arreglos

Las listas y los arrays se comportan de manera similar y ambos son una secuencia ordenada de elementos. También son mutables (CAMBIAN) y no poseen tamaños fijos, lo que quiere decir que pueden crecer y reducirse a lo largo del uso del programa.

Todos los elementos de una lista y un array en Python pueden agregarse y eliminarse. Esto los convierte en objetos muy flexibles y fáciles de trabajar.

Una de las grandes diferencias es que, **a diferencia de los arrays (arreglos), las listas pueden almacenar diversos tipos de datos.**

In [ ]:
#creando un array (arreglo)
import numpy as np

In [ ]:
np.array([0,100]) #Asi se escribe un arreglo ...>Sirve para guardar vectores

array([  0, 100])

In [ ]:
arreglo=[1,2,3] #Vector

arreglo_anidado=[[1,2,3],[2,3,4],[5,6,7]] #Esto es una Matriz

In [ ]:
np.array([1, 2, 3], dtype=complex) #CONVERTIR A UN COMPLEJO


array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
#Convertir una lista en un arreglo

lista=[1,2,3,4]

np.array(lista)

array([1, 2, 3, 4])

In [ ]:
#Función Range (np.arange(p_1, p_2, n))             ------> HACER RANGO DE # DE 0 A 10

np.arange (0,10)

#np.range(0,10,2)                  #-------->#HACER RANGO DE # DE 0-10 DE (2 en 2) cuenta de 2 en 2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
##Ceros y unos: genera arreglos de ceros y unos

np.zeros(3)

np.ones(9) #  ------------------> AGREGAR 9 UNOS

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.zeros((4,6)) # 4 columnas y 6 filas

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

* ¿Cómo crear una matriz con unos en la diagonal y el resto ceros?

In [ ]:
Vector=np.array([1,1,1])
Mat=np.diag(Vector)
print(Mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Función Linspace   -----> para GRAFICAS (Sirve para la simetria de los puntos)

NumPy tiene el método linspace que genera puntos uniformemente espaciados entre dos números.

##Sintaxis

```
np.linspace(a,b,n)   -----> Forma escribir

a=
b=
n= Es la cantidad de datos
```
>Por defecto, linspace genera 50 valores entre a y b


In [ ]:
np.linspace(0,10) #----------> Escribe numeros desde 0 hasta 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

#Ciclos for y while  (mientras esta condicion___haga esto___)

El bucle **for** se utiliza para recorrer los elementos de un objeto iterable (lista, tupla, conjunto, diccionario, …) y ejecutar un bloque de código.

En cada paso de la iteración se tiene en cuenta a un único elemento del objeto iterable, sobre el cuál se pueden aplicar una serie de operaciones.

In [ ]:
lista=[1,2,3,4,5]

for x in lista:
  print(x+1)

2
3
4
5
6


In [ ]:
#Número en rango
for x in range(0,10): #(Pide que me de numero de 0 a 9)
  print(x)

0
1
2
3
4
5
6
7
8
9


In [ ]:
#Ejemplo. Crear una lista con los números del 0 al 10 llamado L1 y luego hacer una lista con los números elevados al cuadrado llamado L2

l1=[x for x in range(0,10)]
print(l1)

l2=[y**2 for y in l1]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Se pueden usar contador y espacio _ para crear funciones que tengan bucles for

In [ ]:
#Ejemplo: Contar los elementos de una lista vacia

def longitud(mi_lista):
    cont = 0
    for x in mi_lista:  #(_ significa para cualquier elemento de la list)
        cont += 1
    return cont

In [ ]:
longitud([1,2,3,4]) #-----------> Medir cuantos elementos hay

4

In [ ]:
#Buscar elementos en una lista

lis=[x for x in range(0,100,2)]

print(lis)

#Buscar

for x in lis:
  if x==10:
    break  #--------> Quiere decir, cuando encuentre el elemento diez PARE!
  print(x)


In [ ]:
#Encontrar el elemento #20 y va de 2 en 2:
for i in lis:
  if i==20:
    break
  print(i)
else:
    print("No se encontro el número")



#While ------>MIENTRAS

El bucle while de Python hace que se ejecute un bloque de código repetidamente mientras una condición sea verdadera. En Python, los bucles while se utilizan principalmente cuando el número de iteraciones necesarias no viene determinado de antemano

In [ ]:
#Ejemplo: Mientras x sea mayor que cero le vamos a restar 1
x=10                         #----Asigno un numero y la condicion es que si es >0 restarle 1 a cada numero

while x>0:
  x-=1
  print(x)

9
8
7
6
5
4
3
2
1
0


In [ ]:
#Pedir al usuario un número entero y agregarlo a una lista si este es par

num=[] #Creamos una lista Vacía

while len(num)<4: #-------->len significa la medida
    valorIngresado = input("Ingrese un numero entero: ")
    valorIngresado = int(valorIngresado)
    if valorIngresado % 2 == 0:
        num.append(valorIngresado)

print(num)

Ingrese un numero entero: 2
Ingrese un numero entero: 0
Ingrese un numero entero: 0
Ingrese un numero entero: 11
Ingrese un numero entero: 6
[2, 0, 0, 6]


#BUCLES ANIDADOS ------------->

Queremos generar todas las combinaciones de de dos números hasta 2.

In [ ]:
# Permutación a generar: ------->UTIL PARA CREAR CONTRASEÑAS
i = 0
j = 0
while i < 3:
    while j < 3:
        print(i,j)
        j += 1
    i += 1
    j = 0

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


#<font color="blue"> Formularios

Recursos de recolección de datos del usuario para aplicar algún codigo con una presentación más agradable

#Input

In [ ]:
#@title SUMA DE VARIABLES { run: "auto", vertical-output: true }
var1 = 56 #@param {type:"number"}
var2 = 34 #@param {type:"number"}

var1+var2

90

In [ ]:
#@title Resta { run: "auto", vertical-output: true }
sust1 = 100 #@param {type:"number"}
sust2 = 45 #@param {type:"number"}
sust3 = 50 #@param {type:"number"}

#codigo

sust1-sust2+sust3

105

#Deslizadores

In [ ]:
#@title slider { run: "auto", vertical-output: true }
var1 = 70 #@param {type:"slider", min:0, max:100, step:1}
var2 = 56 #@param {type:"slider", min:0, max:100, step:1}

x=var1*var2

print(f"El producto entre var1 y var2 es: {x}")

El producto entre var1 y var2 es: 1750


In [ ]:
#@title Derivada { run: "auto", vertical-output: true, form-width: "50%" }
dist = 23 #@param {type:"slider", min:0, max:100, step:1}
time = 17 #@param {type:"slider", min:0, max:50, step:1}


#Velocidad

print(f"La velocidad del objeto x es: {dist/time}")


La velocidad del objeto x es: 1.15


#Caja de datos

In [ ]:
#@title Agregar valores { run: "auto", vertical-output: true }

x = "2" #@param ["1", "2", "3", "4"] {allow-input: true}
y= "1" #@param ["1", "2", "3"]




In [ ]:
#@title caja de datos
listam = "mate" #@param ["mate", "coe", "ingles"]

#Ejemplo

In [ ]:
#@title Encuesta de opinión { run: "auto", vertical-output: true }
candidato = "Mauricio" #@param ["Alberto", "Mauricio", "Ana", "Mari"]

print("Seleccione el candidato de su preferencia: ")

print(candidato)

if candidato == "Mari":
  print("retorne una boleta a Cine")
else:
  print("Gracias por su voto")


Seleccione el candidato de su preferencia: 
Ana
Gracias por su voto


#<font color="red"> Actividad

En grupos de trabajo construir una **calculadora** con las operaciones básicas, además de otras especiales como raiz, seno o exponencial (sean creativos) ☝

Para ello, use funciones como if,else, elif, además de algunos ciclos while (opcional) solo para que la calculadora se ejecute "sola".

Se debe usar  **Formulario de Colab**

#  Laboratorio #1
En grupos de trabajo: Construir un simulador de **Cajero automático.**

El simulador debe contener las funciones básicas como

1. Consultar saldo
2. Depositar
3. Retirar
4. Ingreso de contraseña** opcional
5. Tranferir dinero
6. Salir

Entre otras

>Se recomiendo usar la función Range para generar saldos iniciales aleatorios.

Use ciclos while y for además funciones como if, else, elif, input ebtre otras.

###Sean creativos e ingeniosos :)

Fceha de entrega: Jueves 23 de Febrero vía Intu

In [ ]:
#@title Texto de título predeterminado { run: "auto", vertical-output: true }
x = 5 #@param {type:"number"}
y = 45 #@param {type:"number"}
Oper = "producto" #@param ["suma", "resta", "producto"]


if Oper=="suma":
  print(x+y)
elif Oper=="resta":
  print(x-y)
elif Oper=="producto":
  print(x*y)
else:
 print("***Ha terminado***")