<a href="https://colab.research.google.com/github/YasminGarcia1210/MAT_APLICADAS03/blob/main/CUADERNO_2_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src=http://www.acofi.edu.co/eiei2016/wp-content/uploads/2016/09/Logo-Universidad-ICESI.jpg width="200" height="200" align="center">

#**<big><big>Matemáticas Aplicadas I</big></big><br><small>FIDCA  Facultad de Ingeniería, diseño y ciencias exactas </small><br><small>_*CUADERNO 2*_ ARREGLOS. </small>**

##Arreglos #

Un **array** en Python es un tipo de variable especial que puede alojar dentro de sí varios valores al mismo tiempo.

Es decir, no es que se alojen los datos en un mismo lugar al mismo tiempo, sino que se tienen una serie de contenedores que conforman el array y en cada uno de esos contenedores se guardan datos distintos

##Diferencias entre listas y arreglos

Las listas y los arrays se comportan de manera similar y ambos son una secuencia ordenada de elementos. También son mutables (CAMBIAN) y no poseen tamaños fijos, lo que quiere decir que pueden crecer y reducirse a lo largo del uso del programa.

Todos los elementos de una lista y un array en Python pueden agregarse y eliminarse. Esto los convierte en objetos muy flexibles y fáciles de trabajar.

Una de las grandes diferencias es que, **a diferencia de los arrays (arreglos), las listas pueden almacenar diversos tipos de datos.**

In [ ]:
#creando un array (arreglo)
import numpy as np

In [ ]:
np.array([0,100]) #Asi se escribe un arreglo ...>Sirve para guardar vectores

array([  0, 100])

In [ ]:
arreglo=[1,2,3] #Vector

arreglo_anidado=[[1,2,3],[2,3,4],[5,6,7]] #Esto es una Matriz

In [ ]:
np.array([1, 2, 3], dtype=complex) #CONVERTIR A UN COMPLEJO


array([1.+0.j, 2.+0.j, 3.+0.j])

In [ ]:
ma=[[1., 2., 3.], [1,2,3], [1+1.j, 2+2.j, 5.j]]
ma

[[1.0, 2.0, 3.0], [1, 2, 3], [(1+1j), (2+2j), 5j]]

In [ ]:
#Convertir una lista en un arreglo

lista=[1,2,3,4]
print(lista)
np.array(lista)

[1, 2, 3, 4]


array([1, 2, 3, 4])

In [ ]:
#Función Range (np.arange(p_1, p_2, n))             ------> HACER RANGO DE # DE 0 A 10

#np.arange (0,10) #Todos los numeros entre 0 y 9

np.arange(0,101,2)#-------->#HACER RANGO DE # DE 0-100 DE (2 en 2) cuenta de 2 en 2

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [ ]:
##Ceros y unos en el vector: genera arreglos de ceros y unos
#np.zeros(3)
np.ones(9) #  ------------------> AGREGAR 9 UNOS

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# ceros y unos en la matriz

np.zeros((4,6)) # 4 filas y 6 columnas

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.identity(3) #Matriz identidad

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Vector=np.array([1,1,1])
Mat=np.diag(Vector)
print(Mat)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
A=[[1,2,3], [5,6,7],[4,5,6]]
A

[[1, 2, 3], [5, 6, 7], [4, 5, 6]]

In [ ]:
np.dot(A,Mat)

array([[1, 2, 3],
       [5, 6, 7],
       [4, 5, 6]])

# Función Linspace   -----> para GRAFICAS (Sirve para la simetria de los puntos)

NumPy tiene el método linspace que genera puntos uniformemente espaciados entre dos números.

##Sintaxis

```
np.linspace(a,b,n)   -----> Forma escribir

a=
b=
n= Es la cantidad de datos
```
>Por defecto, linspace genera 50 valores entre a y b


In [ ]:
np.linspace(0,10,100) #----------> Escribe numeros desde 0 hasta 10

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

#Ciclos for y while  (mientras esta condicion___haga esto___)

El bucle **for** se utiliza para recorrer los elementos de un objeto iterable (lista, tupla, conjunto, diccionario, …) y ejecutar un bloque de código.

En cada paso de la iteración se tiene en cuenta a un único elemento del objeto iterable, sobre el cuál se pueden aplicar una serie de operaciones.

In [ ]:
lista=[1,2,3,4,5]

for x in lista:
  pri  nt(x**2)

1
4
9
16
25


In [ ]:
#Número en rango
for x in range(0,10): #(Pide que me de numero de 0 a 9)
  print(x-5)

-5
-4
-3
-2
-1
0
1
2
3
4


In [ ]:
#Ejemplo. Crear una lista con los números del 0 al 10 llamado L1 y luego hacer una lista con los números elevados al cuadrado llamado L2

l1=[x for x in range(0,10)]
print(l1)

l2=[y**2 for y in l1]
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

Se pueden usar contador y espacio _ para crear funciones que tengan bucles for

In [ ]:
#Ejemplo: Contar los elementos de una lista vacia

def longitud(mi_lista):
    cont = 0 #Contador
    for x in mi_lista:  #(_ significa para cualquier elemento de la list)
        cont += 1
    return cont

In [ ]:
longitud([1,2,3,4,6,12,15]) #-----------> Medir cuantos elementos hay

7

In [ ]:
#Buscar elementos en una lista

lis=[x for x in range(0,15,2)]

print(lis)

#Buscar

for x in lis:
  if x==10:
    break  #--------> Quiere decir, cuando encuentre el elemento diez PARE!
  print((x))


[0, 2, 4, 6, 8, 10, 12, 14]
0
2
4
6
8


In [ ]:
#Encontrar el elemento #20 y va de 2 en 2:
for i in lis:
  if i==20:
    break
  print(i)
else:
    print("No se encontro el número")



0
2
4
6
8
10
12
14
No se encontro el número


#While ------>MIENTRAS

El bucle while de Python hace que se ejecute un bloque de código repetidamente mientras una condición sea verdadera. En Python, los bucles while se utilizan principalmente cuando el número de iteraciones necesarias no viene determinado de antemano

In [4]:
#Ejemplo:
i=0
while i<=5:
    i+=1  #i=i+1
    print (i)


1
2
3
4
5
6


In [ ]:
i=0
while i<10:
  i=i+1
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
#Ejemplo: Mientras x sea mayor que cero le vamos a restar 1
x=10

while x>0:
  x-=1
  print(x)

9
8
7
6
5
4
3
2
1
0


Ejemplo muy util: Pedir al usuario un número entero y agregarlo a una lista con longitud dada, solo si este es par

In [5]:
num=[] #Creamos una lista Vacía

while len(num)<5: #-------->len significa la medida
    valorIngresado = input("Ingrese un numero entero: ")
    valorIngresado = int(valorIngresado)
    if valorIngresado % 2 == 0:
        num.append(valorIngresado)

    print("Lista:", num)


Ingrese un numero entero: 10
Lista: [10]
Ingrese un numero entero: 9
Lista: [10]
Ingrese un numero entero: 3
Lista: [10]
Ingrese un numero entero: 7
Lista: [10]
Ingrese un numero entero: 2
Lista: [10, 2]
Ingrese un numero entero: 4
Lista: [10, 2, 4]
Ingrese un numero entero: 6
Lista: [10, 2, 4, 6]
Ingrese un numero entero: 5
Lista: [10, 2, 4, 6]
Ingrese un numero entero: 0
Lista: [10, 2, 4, 6, 0]


#BUCLES ANIDADOS ------------->

Queremos generar todas las combinaciones de de dos números hasta 2.

In [ ]:
# Permutación a generar: ------->UTIL PARA CREAR CONTRASEÑAS
i = 0
j = 0
while i < 3:
    while j < 3:
        print(i,j)
        j += 1
    i += 1
    j = 0

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


# Tablas de Multiplicar

In [8]:
def imprimir_tabla(numero):

    limite = 12
    contador = 1

    while contador <= limite:
        resultado = contador * numero
        print("{} x {} = {}".format(numero, contador, resultado))
        # Incrementar contador para no caer en ciclo infinito
        contador = contador + 1

# Probar función
imprimir_tabla(8)


8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80
8 x 11 = 88
8 x 12 = 96


#<font color="lightblue"> Formularios

Recursos de recolección de datos del usuario para aplicar algún codigo con una presentación más agradable

#Input

In [19]:
# @title calculadora { run: "auto", vertical-output: true }
numero_1 = 98 # @param {type:"number"}
numero_2 = 41 # @param {type:"number"}

print("el resultado de la suma es", numero_1 + numero_2)
print("el resultado de la resta es", numero_1 - numero_2)
print("el resultado de la multiplicacion es", numero_1 * numero_2)
print("el resultado de la division es", numero_1 / numero_2)

el resultado de la suma es 139
el resultado de la resta es 57
el resultado de la multiplicacion es 4018
el resultado de la division es 2.3902439024390243


#Deslizadores

In [ ]:
# @title Texto de título predeterminado { run: "auto", vertical-output: true }
deslizador = 1 # @param {type:"slider", min:1, max:50, step:1}

deslizador*8

320

In [ ]:
#@title slider { run: "auto", vertical-output: true }
var1 = 42 #@param {type:"slider", min:0, max:100, step:1}
var2 = 30 #@param {type:"slider", min:0, max:100, step:1}

x=var1*var2

print(f"El producto entre var1 y var2 es: {x}")

El producto entre var1 y var2 es: 1927


In [26]:
#@title Velocidad { run: "auto", vertical-output: true, form-width: "50%" }
dist = 31 #@param {type:"slider", min:0, max:100, step:1}
time = 22 #@param {type:"slider", min:0, max:50, step:1}


#Velocidad

print(f"La velocidad del objeto x es: {dist/time}")


La velocidad del objeto x es: 1.4090909090909092


#Caja de datos

In [37]:
# @title OPERACIONES { run: "auto", vertical-output: true, form-width: "60%" }
operacion = "resta" # @param ["suma","resta","producto","cociente"]
X = 1 # @param {type:"number"}
Y = 10 # @param {type:"number"}

if operacion=="suma":
    print(X+Y)
elif operacion=="resta":
    print(X-Y)
elif operacion=="producto":
    print(X*Y)
elif operacion=="cociente":
    print(X/Y)

-9


#Ejemplo

In [ ]:
#@title Encuesta de opinión { run: "auto", vertical-output: true }
candidato = "Ana" #@param ["Alberto", "Mauricio", "Ana", "Mari"]

print("Seleccione el candidato de su preferencia: ")

print(candidato)

if candidato == "Mari":
  print("retorne una boleta a Cine")
else:
  print("Gracias por su voto")


Seleccione el candidato de su preferencia: 
Ana
Gracias por su voto


#<font color="red"> Actividad

En grupos de trabajo construir una **calculadora** con las operaciones básicas, además de otras especiales como raiz, seno o exponencial (sean creativos) ☝

Para ello, use funciones como if,else, elif, además de algunos ciclos while (opcional) solo para que la calculadora se ejecute "sola".

Se debe usar  **Formulario de Colab**

#  Laboratorio # 1
En grupos de trabajo: Construir un simulador de **Cajero automático.**

El simulador debe contener las funciones básicas como

1. Consultar saldo
2. Depositar
3. Retirar
4. Ingreso de contraseña** opcional
5. Tranferir dinero
6. Salir

Entre otras

>Se recomiendo usar la función Range  o linspace para generar saldos iniciales aleatorios.

Use ciclos while y for además funciones como if, else, elif, input entre otras.

###Sean creativos e ingeniosos :)


# Para la proxima clase

### Trazado de curvas y visualización

[Libreria de MatplotLib](https://matplotlib.org/) Explorar

[Ejemplos de Graficas](https://matplotlib.org/stable/gallery/index.html) En este enlace podrás encontrar la sintaxis basica para la construcción de media y alta calidad